### ISSUE TITLE
Implement full IRI validation

### ISSUE THREAD

**Issue by Tpt** [Tpt/rio#13]
The `Iri` parser should properly validate the IRI using the RFC grammar instead of just trying to properly split the the IRI into its different components.

**Comment by pchampin** [comment]
I have a (supposedly) complete implementation in sophia: https://github.com/pchampin/sophia_rs/blob/master/sophia/src/term/iri_rfc3987.rs .
It currently uses a mix of [pest](https://github.com/pchampin/sophia_rs/blob/master/sophia/src/term/iri_rfc3987.rs) and regexps. I'd like to reduce dependencies and stick to regexps (they are faster). But once it is done, I can release it as a separate crate, and you could possibly reuse it here.

Let me know what you think about it.

**Comment by Tpt** [comment]
Thank you for the proposal! I already implemented a significant part of the parser here in "vanilla" Rust: https://github.com/Tpt/rio/blob/master/api/src/iri.rs
I hope to be able to complete the parser and have something that does not depends on anything except the std (or core?) library. 
Hopefully it will be even faster than regex (it would be something interesting to benchmark).
