### ISSUE TITLE
Turtleparser throw error with relative Iri whereas it shouldn't

### ISSUE THREAD

**Issue by YruamaLairba** [Tpt/rio#21]
Hello, i was testing rio_turtle to see if it's usable for one of my project and i get trouble when my rdf contain a relative iri. When the TurtleParser encounter a relative iri, it return an error about missing scheme whereas it shouldn't because it's a relative iri and [relative iri are allowed in turtle](https://www.w3.org/TR/turtle/#sec-iri).
Worst, Seems there is no way to skip an error and continuing to parse. I tried to do it with a iterator, an when i encounter an error, the iterator stuck on it (try my joined code with my joined ttl). i didn't find a way to get the content of faulty iri either. In a general context, these two elements doesn't permit to be error tolerant when parsing.

I think the origin of this issue is the iri datatypes, it doesn't allow relative iri. In more general, I think you should allow the existence of unchecked or invalid iri and let the user check it if it's needed, or maybe the check should be done by the parser itself ?

[lv2core.ttl.txt](https://github.com/Tpt/rio/files/4352275/lv2core.ttl.txt)
[main.rs.txt](https://github.com/Tpt/rio/files/4352276/main.rs.txt)

**Comment by Tpt** [comment]
Hi! Thank you for your interest in the library and sorry for the bug you encounter.

I have not implemented parse error recovery yet in the Turtle/TriG parser. It's already done for the NTriples/NQuads parser.

The IRI parser was very strict and not allowing relative IRIs when the base IRI has a path without "/" (like in the invalid "file:foo"). I just pushed a change that allows to resolve such IRIs. Your file should parse without problems now.

Please close the issue if it works for you too.
