### ISSUE TITLE
IRI normalization and validation

### ISSUE THREAD

**Issue by Tpt** [Tpt/rio#7]
I believe that the library should fully validate and normalize IRIs.

Missing features:
* Full IRI validation (host...)
* UTF-8 normalization using NFC

**Comment by pchampin** [comment]
> Full IRI validation (host...)

What do you mean for host? Checking that the host exists?

> UTF-8 normalization using NFC

This might be contrary to the RDF specs, which [states](https://www.w3.org/TR/rdf11-concepts/#dfn-iri-equality):
> IRI equality: Two IRIs are equal if and only if they are equivalent under Simple String Comparison according to [section 5.1](https://tools.ietf.org/html/rfc3987#section-5.1) of [RFC3987]. Further normalization MUST NOT be performed when comparing IRIs for equality.

**Comment by Tpt** [comment]
>What do you mean for host? Checking that the host exists?

No, I was thinking about [Punycode](https://fr.wikipedia.org/wiki/Punycode). But this normalization seems to be out of scope of RDF according the the spec paragraph.
